### ISSUE TITLE
Switching account in Metamask doesn't change it in dApp

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/dapp-wrose#4]
Steps to reproduce:
1. Open https://wrose.oasis.io, click Connect Wallet
2. Metamask pops up, select an account
3. Account address is shown in the top-right corner of dApp (0x.... Sapphire Testnet)
4. Open Metamask again, connect and select a different account
5. The old account address is still shown in the top-right corner.

Expected behavior:
When the account is switched in Metamask, it should also be updated in the dApp.

**Comment by lubej** [comment]
Yeah, couple of things are not handled yet https://github.com/oasisprotocol/dapp-wrose/pull/2#discussion_r1396937630. 

So when working on the above issue,
- network switch
- disconnect from app

Should be handled as well.
